trigger: 
  - master

name: Xmf2.Common.Extensions-CI-$(SourceBranchName)-$(Date:yyyyMMdd)$(Rev:.r)

pool:
  vmImage: windows-latest

steps:
  - checkout: self
    clean: true
  
  - task: DotNetCoreCLI@2
    inputs:
      command: 'pack'
      packagesToPack: 'Xmf2.Common.Extensions.csproj'
      configuration: 'Release'
      versioningScheme: 'off'
    condition: succeeded()

  - task: PublishBuildArtifacts@1
    displayName: "Publish Artifact: drop"
    condition: succeeded()